// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.DAL.Repositories;

#nullable disable

namespace TM.DAL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskVersionId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.TaskVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstUpdater")
                        .HasColumnType("int");

                    b.Property<int>("LastUpdater")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId")
                        .IsUnique()
                        .HasFilter("[CurrentVersionId] IS NOT NULL");

                    b.HasIndex("FirstUpdater");

                    b.HasIndex("LastUpdater");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.Document", b =>
                {
                    b.HasOne("TM.DAL.Entities.AppEntities.UserTask", "Task")
                        .WithMany("Documents")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TM.DAL.Entities.AppEntities.TaskVersion", null)
                        .WithMany("Documents")
                        .HasForeignKey("TaskVersionId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.TaskVersion", b =>
                {
                    b.HasOne("TM.DAL.Entities.AppEntities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TM.DAL.Entities.AppEntities.UserTask", "Task")
                        .WithMany("Versions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.UserTask", b =>
                {
                    b.HasOne("TM.DAL.Entities.AppEntities.TaskVersion", "CurrentVersion")
                        .WithOne()
                        .HasForeignKey("TM.DAL.Entities.AppEntities.UserTask", "CurrentVersionId");

                    b.HasOne("TM.DAL.Entities.AppEntities.User", null)
                        .WithMany()
                        .HasForeignKey("FirstUpdater")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TM.DAL.Entities.AppEntities.User", null)
                        .WithMany()
                        .HasForeignKey("LastUpdater")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.TaskVersion", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TM.DAL.Entities.AppEntities.UserTask", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
